# Generated by Django 4.1.7 on 2023-03-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
