# Generated by Django 4.1.7 on 2023-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '1-Bolim',
                'verbose_name_plural': '1-Bolim',
            },
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '2-Bolim',
                'verbose_name_plural': '2-Bolim',
            },
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '3-Bolim',
                'verbose_name_plural': '3-Bolim',
            },
        ),
        migrations.CreateModel(
            name='Section4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '4-Bolim',
                'verbose_name_plural': '4-Bolim',
            },
        ),
    ]
