# Generated by Django 4.1.7 on 2023-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=1000)),
                ('button_link', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': "5-Bo'lim",
                'verbose_name_plural': "5-Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Section6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=1000)),
                ('button_link', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': "6-Bo'lim",
                'verbose_name_plural': "6-Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Section7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=1000)),
                ('button_link', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': "7-Bo'lim",
                'verbose_name_plural': "7-Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Section8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=1000)),
                ('button_link', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': "8-Bo'lim",
                'verbose_name_plural': "8-Bo'lim",
            },
        ),
    ]
