# Generated by Django 4.1.7 on 2023-03-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0002_section5_section6_section7_section8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section8',
            new_name='Section5to8',
        ),
        migrations.DeleteModel(
            name='Section5',
        ),
        migrations.DeleteModel(
            name='Section6',
        ),
        migrations.DeleteModel(
            name='Section7',
        ),
        migrations.AlterModelOptions(
            name='section5to8',
            options={'verbose_name': "5-8 Bo'lim", 'verbose_name_plural': "5-8 Bo'lim"},
        ),
    ]
