# Generated by Django 4.1.7 on 2023-03-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0003_rename_section8_section5to8_delete_section5_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section5to8',
            options={'verbose_name': "5-dan 8-gacha Bo'lim", 'verbose_name_plural': "5-dan 8-gacha Bo'lim"},
        ),
    ]
