# Generated by Django 4.1.7 on 2023-03-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0004_alter_section5to8_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section5to8',
            options={'verbose_name': "Bo'lim 5-dan 8-gacha", 'verbose_name_plural': "Bo'lim 5-dan 8-gacha"},
        ),
    ]
