# Generated by Django 4.1.7 on 2023-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0005_alter_section5to8_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section9to10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='images/')),
                ('button_name', models.CharField(max_length=600)),
                ('button_link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': "BO'lim 9-dan 10-gacha",
                'verbose_name_plural': "BO'lim 9-dan 10-gacha",
            },
        ),
    ]
