# Generated by Django 4.1.7 on 2023-03-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0006_section9to10'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section9to10',
            options={'verbose_name': "Bo'lim 9-dan 10-gacha", 'verbose_name_plural': "Bo'lim 9-dan 10-gacha"},
        ),
    ]
