# Generated by Django 4.1.7 on 2023-03-14 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0008_section11plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section9to10',
            name='subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='section9to10',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
