# Generated by Django 4.1.7 on 2023-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sections', '0009_alter_section9to10_subtitle_alter_section9to10_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section9to10',
            name='subtitle',
            field=models.CharField(max_length=1000),
        ),
    ]
