# Generated by Django 4.1.7 on 2023-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_telegrambot_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='images/')),
                ('subtitle', models.CharField(max_length=600)),
                ('title', models.TextField()),
                ('button_name', models.CharField(max_length=600)),
                ('button_link', models.CharField(max_length=6000)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Slider',
            },
        ),
    ]
